// config-pg.ts 现在是桶文件，所有实现已迁移到 src/services/config/ 目录。
// 保持此文件以兼容现有 import 路径。

export type {
  AgentConfigUpsertData,
  AgentFullConfig,
  AgentKnowledgeConfig,
  McpServerConfig,
  McpServerInfoOutput,
  McpServerSetOptions,
  ModelCostConfig,
  ModelLimitConfig,
  ModelModalities,
  ModelOptions,
  PermissionAction,
  PermissionConfig,
  ProviderExtraOptions,
  ProviderUpsertData,
  ResourceAccess,
  ResourceAccessInput,
  SkillConfigRowWithAccess,
  SkillMetadata,
  SkillSetOptions,
  SkillUpsertData,
  UserConfigData,
} from "./config/index";
export {
  AGENT_SETTABLE_FIELDS,
  addModel,
  assertMcpServerInternalWritable,
  createAgentConfig,
  createMcpServer,
  deleteAgentConfig,
  deleteMcpServer,
  deleteProvider,
  deleteSkill,
  getAgentConfig,
  getAgentConfigById,
  getAgentFullConfig,
  getMcpServer,
  getMcpServerByResourceKey,
  getProvider,
  getSkill,
  getSkillByResourceKey,
  getUserConfig,
  listAgentConfigs,
  listAgentSkillIds,
  listMcpServers,
  listProviders,
  listSkills,
  removeModel,
  setMcpServerEnabled,
  setUserConfig,
  syncAgentSkills,
  updateAgentConfig,
  updateMcpServer,
  updateModel,
  upsertProvider,
  upsertSkill,
} from "./config/index";
