/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AgentPanelRouteImport } from "./routes/agent/_panel"
import { Route as AgentAgentIdRouteImport } from "./routes/agent/$agentId"
import { Route as AppWorkflowRouteImport } from "./routes/_app/workflow"
import { Route as AppTasksRouteImport } from "./routes/_app/tasks"
import { Route as AppSkillsRouteImport } from "./routes/_app/skills"
import { Route as AppOrganizationsRouteImport } from "./routes/_app/organizations"
import { Route as AppModelsRouteImport } from "./routes/_app/models"
import { Route as AppMcpRouteImport } from "./routes/_app/mcp"
import { Route as AppKnowledgeBasesRouteImport } from "./routes/_app/knowledge-bases"
import { Route as AppEnvironmentsRouteImport } from "./routes/_app/environments"
import { Route as AppChannelsRouteImport } from "./routes/_app/channels"
import { Route as AppApikeysRouteImport } from "./routes/_app/apikeys"
import { Route as AppAgentsRouteImport } from "./routes/_app/agents"
import { Route as AppSessionIdRouteImport } from "./routes/_app/$sessionId"
import { Route as AgentPanelIndexRouteImport } from "./routes/agent/_panel/index"
import { Route as AgentPanelWorkflowRouteImport } from "./routes/agent/_panel/workflow"
import { Route as AgentPanelTasksRouteImport } from "./routes/agent/_panel/tasks"
import { Route as AgentPanelSkillsRouteImport } from "./routes/agent/_panel/skills"
import { Route as AgentPanelSessionsRouteImport } from "./routes/agent/_panel/sessions"
import { Route as AgentPanelOrganizationsRouteImport } from "./routes/agent/_panel/organizations"
import { Route as AgentPanelModelsRouteImport } from "./routes/agent/_panel/models"
import { Route as AgentPanelMcpRouteImport } from "./routes/agent/_panel/mcp"
import { Route as AgentPanelKnowledgeBasesRouteImport } from "./routes/agent/_panel/knowledge-bases"
import { Route as AgentPanelDashboardRouteImport } from "./routes/agent/_panel/dashboard"
import { Route as AgentPanelChannelsRouteImport } from "./routes/agent/_panel/channels"
import { Route as AgentPanelApikeysRouteImport } from "./routes/agent/_panel/apikeys"
import { Route as AgentAgentIdSessionIdRouteImport } from "./routes/agent/$agentId_.$sessionId"
import { Route as AppWorkflowSplatRouteImport } from "./routes/_app/workflow_.$"
import { Route as AgentPanelChatAgentIdRouteImport } from "./routes/agent/_panel/chat.$agentId"
import { Route as AgentPanelChatAgentIdSessionIdRouteImport } from "./routes/agent/_panel/chat.$agentId_.$sessionId"

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AgentPanelRoute = AgentPanelRouteImport.update({
  id: "/agent/_panel",
  path: "/agent",
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAgentIdRoute = AgentAgentIdRouteImport.update({
  id: "/agent/$agentId",
  path: "/agent/$agentId",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowRoute = AppWorkflowRouteImport.update({
  id: "/workflow",
  path: "/workflow",
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AppRoute,
} as any)
const AppSkillsRoute = AppSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AppRoute,
} as any)
const AppModelsRoute = AppModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => AppRoute,
} as any)
const AppMcpRoute = AppMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBasesRoute = AppKnowledgeBasesRouteImport.update({
  id: "/knowledge-bases",
  path: "/knowledge-bases",
  getParentRoute: () => AppRoute,
} as any)
const AppEnvironmentsRoute = AppEnvironmentsRouteImport.update({
  id: "/environments",
  path: "/environments",
  getParentRoute: () => AppRoute,
} as any)
const AppChannelsRoute = AppChannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => AppRoute,
} as any)
const AppApikeysRoute = AppApikeysRouteImport.update({
  id: "/apikeys",
  path: "/apikeys",
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsRoute = AppAgentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: "/$sessionId",
  path: "/$sessionId",
  getParentRoute: () => AppRoute,
} as any)
const AgentPanelIndexRoute = AgentPanelIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelWorkflowRoute = AgentPanelWorkflowRouteImport.update({
  id: "/workflow",
  path: "/workflow",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelTasksRoute = AgentPanelTasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelSkillsRoute = AgentPanelSkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelSessionsRoute = AgentPanelSessionsRouteImport.update({
  id: "/sessions",
  path: "/sessions",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelOrganizationsRoute = AgentPanelOrganizationsRouteImport.update({
  id: "/organizations",
  path: "/organizations",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelModelsRoute = AgentPanelModelsRouteImport.update({
  id: "/models",
  path: "/models",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelMcpRoute = AgentPanelMcpRouteImport.update({
  id: "/mcp",
  path: "/mcp",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelKnowledgeBasesRoute =
  AgentPanelKnowledgeBasesRouteImport.update({
    id: "/knowledge-bases",
    path: "/knowledge-bases",
    getParentRoute: () => AgentPanelRoute,
  } as any)
const AgentPanelDashboardRoute = AgentPanelDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelChannelsRoute = AgentPanelChannelsRouteImport.update({
  id: "/channels",
  path: "/channels",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelApikeysRoute = AgentPanelApikeysRouteImport.update({
  id: "/apikeys",
  path: "/apikeys",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentAgentIdSessionIdRoute = AgentAgentIdSessionIdRouteImport.update({
  id: "/agent/$agentId_/$sessionId",
  path: "/agent/$agentId/$sessionId",
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowSplatRoute = AppWorkflowSplatRouteImport.update({
  id: "/workflow_/$",
  path: "/workflow/$",
  getParentRoute: () => AppRoute,
} as any)
const AgentPanelChatAgentIdRoute = AgentPanelChatAgentIdRouteImport.update({
  id: "/chat/$agentId",
  path: "/chat/$agentId",
  getParentRoute: () => AgentPanelRoute,
} as any)
const AgentPanelChatAgentIdSessionIdRoute =
  AgentPanelChatAgentIdSessionIdRouteImport.update({
    id: "/chat/$agentId_/$sessionId",
    path: "/chat/$agentId/$sessionId",
    getParentRoute: () => AgentPanelRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/login": typeof LoginRoute
  "/$sessionId": typeof AppSessionIdRoute
  "/agents": typeof AppAgentsRoute
  "/apikeys": typeof AppApikeysRoute
  "/channels": typeof AppChannelsRoute
  "/environments": typeof AppEnvironmentsRoute
  "/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/mcp": typeof AppMcpRoute
  "/models": typeof AppModelsRoute
  "/organizations": typeof AppOrganizationsRoute
  "/skills": typeof AppSkillsRoute
  "/tasks": typeof AppTasksRoute
  "/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/agent": typeof AgentPanelRouteWithChildren
  "/workflow/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId/$sessionId": typeof AgentAgentIdSessionIdRoute
  "/agent/apikeys": typeof AgentPanelApikeysRoute
  "/agent/channels": typeof AgentPanelChannelsRoute
  "/agent/dashboard": typeof AgentPanelDashboardRoute
  "/agent/knowledge-bases": typeof AgentPanelKnowledgeBasesRoute
  "/agent/mcp": typeof AgentPanelMcpRoute
  "/agent/models": typeof AgentPanelModelsRoute
  "/agent/organizations": typeof AgentPanelOrganizationsRoute
  "/agent/sessions": typeof AgentPanelSessionsRoute
  "/agent/skills": typeof AgentPanelSkillsRoute
  "/agent/tasks": typeof AgentPanelTasksRoute
  "/agent/workflow": typeof AgentPanelWorkflowRoute
  "/agent/": typeof AgentPanelIndexRoute
  "/agent/chat/$agentId": typeof AgentPanelChatAgentIdRoute
  "/agent/chat/$agentId/$sessionId": typeof AgentPanelChatAgentIdSessionIdRoute
}
export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/$sessionId": typeof AppSessionIdRoute
  "/agents": typeof AppAgentsRoute
  "/apikeys": typeof AppApikeysRoute
  "/channels": typeof AppChannelsRoute
  "/environments": typeof AppEnvironmentsRoute
  "/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/mcp": typeof AppMcpRoute
  "/models": typeof AppModelsRoute
  "/organizations": typeof AppOrganizationsRoute
  "/skills": typeof AppSkillsRoute
  "/tasks": typeof AppTasksRoute
  "/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/": typeof AppIndexRoute
  "/workflow/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId/$sessionId": typeof AgentAgentIdSessionIdRoute
  "/agent/apikeys": typeof AgentPanelApikeysRoute
  "/agent/channels": typeof AgentPanelChannelsRoute
  "/agent/dashboard": typeof AgentPanelDashboardRoute
  "/agent/knowledge-bases": typeof AgentPanelKnowledgeBasesRoute
  "/agent/mcp": typeof AgentPanelMcpRoute
  "/agent/models": typeof AgentPanelModelsRoute
  "/agent/organizations": typeof AgentPanelOrganizationsRoute
  "/agent/sessions": typeof AgentPanelSessionsRoute
  "/agent/skills": typeof AgentPanelSkillsRoute
  "/agent/tasks": typeof AgentPanelTasksRoute
  "/agent/workflow": typeof AgentPanelWorkflowRoute
  "/agent": typeof AgentPanelIndexRoute
  "/agent/chat/$agentId": typeof AgentPanelChatAgentIdRoute
  "/agent/chat/$agentId/$sessionId": typeof AgentPanelChatAgentIdSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/login": typeof LoginRoute
  "/_app/$sessionId": typeof AppSessionIdRoute
  "/_app/agents": typeof AppAgentsRoute
  "/_app/apikeys": typeof AppApikeysRoute
  "/_app/channels": typeof AppChannelsRoute
  "/_app/environments": typeof AppEnvironmentsRoute
  "/_app/knowledge-bases": typeof AppKnowledgeBasesRoute
  "/_app/mcp": typeof AppMcpRoute
  "/_app/models": typeof AppModelsRoute
  "/_app/organizations": typeof AppOrganizationsRoute
  "/_app/skills": typeof AppSkillsRoute
  "/_app/tasks": typeof AppTasksRoute
  "/_app/workflow": typeof AppWorkflowRoute
  "/agent/$agentId": typeof AgentAgentIdRoute
  "/agent/_panel": typeof AgentPanelRouteWithChildren
  "/_app/": typeof AppIndexRoute
  "/_app/workflow_/$": typeof AppWorkflowSplatRoute
  "/agent/$agentId_/$sessionId": typeof AgentAgentIdSessionIdRoute
  "/agent/_panel/apikeys": typeof AgentPanelApikeysRoute
  "/agent/_panel/channels": typeof AgentPanelChannelsRoute
  "/agent/_panel/dashboard": typeof AgentPanelDashboardRoute
  "/agent/_panel/knowledge-bases": typeof AgentPanelKnowledgeBasesRoute
  "/agent/_panel/mcp": typeof AgentPanelMcpRoute
  "/agent/_panel/models": typeof AgentPanelModelsRoute
  "/agent/_panel/organizations": typeof AgentPanelOrganizationsRoute
  "/agent/_panel/sessions": typeof AgentPanelSessionsRoute
  "/agent/_panel/skills": typeof AgentPanelSkillsRoute
  "/agent/_panel/tasks": typeof AgentPanelTasksRoute
  "/agent/_panel/workflow": typeof AgentPanelWorkflowRoute
  "/agent/_panel/": typeof AgentPanelIndexRoute
  "/agent/_panel/chat/$agentId": typeof AgentPanelChatAgentIdRoute
  "/agent/_panel/chat/$agentId_/$sessionId": typeof AgentPanelChatAgentIdSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/login"
    | "/$sessionId"
    | "/agents"
    | "/apikeys"
    | "/channels"
    | "/environments"
    | "/knowledge-bases"
    | "/mcp"
    | "/models"
    | "/organizations"
    | "/skills"
    | "/tasks"
    | "/workflow"
    | "/agent/$agentId"
    | "/agent"
    | "/workflow/$"
    | "/agent/$agentId/$sessionId"
    | "/agent/apikeys"
    | "/agent/channels"
    | "/agent/dashboard"
    | "/agent/knowledge-bases"
    | "/agent/mcp"
    | "/agent/models"
    | "/agent/organizations"
    | "/agent/sessions"
    | "/agent/skills"
    | "/agent/tasks"
    | "/agent/workflow"
    | "/agent/"
    | "/agent/chat/$agentId"
    | "/agent/chat/$agentId/$sessionId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/$sessionId"
    | "/agents"
    | "/apikeys"
    | "/channels"
    | "/environments"
    | "/knowledge-bases"
    | "/mcp"
    | "/models"
    | "/organizations"
    | "/skills"
    | "/tasks"
    | "/workflow"
    | "/agent/$agentId"
    | "/"
    | "/workflow/$"
    | "/agent/$agentId/$sessionId"
    | "/agent/apikeys"
    | "/agent/channels"
    | "/agent/dashboard"
    | "/agent/knowledge-bases"
    | "/agent/mcp"
    | "/agent/models"
    | "/agent/organizations"
    | "/agent/sessions"
    | "/agent/skills"
    | "/agent/tasks"
    | "/agent/workflow"
    | "/agent"
    | "/agent/chat/$agentId"
    | "/agent/chat/$agentId/$sessionId"
  id:
    | "__root__"
    | "/_app"
    | "/login"
    | "/_app/$sessionId"
    | "/_app/agents"
    | "/_app/apikeys"
    | "/_app/channels"
    | "/_app/environments"
    | "/_app/knowledge-bases"
    | "/_app/mcp"
    | "/_app/models"
    | "/_app/organizations"
    | "/_app/skills"
    | "/_app/tasks"
    | "/_app/workflow"
    | "/agent/$agentId"
    | "/agent/_panel"
    | "/_app/"
    | "/_app/workflow_/$"
    | "/agent/$agentId_/$sessionId"
    | "/agent/_panel/apikeys"
    | "/agent/_panel/channels"
    | "/agent/_panel/dashboard"
    | "/agent/_panel/knowledge-bases"
    | "/agent/_panel/mcp"
    | "/agent/_panel/models"
    | "/agent/_panel/organizations"
    | "/agent/_panel/sessions"
    | "/agent/_panel/skills"
    | "/agent/_panel/tasks"
    | "/agent/_panel/workflow"
    | "/agent/_panel/"
    | "/agent/_panel/chat/$agentId"
    | "/agent/_panel/chat/$agentId_/$sessionId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AgentAgentIdRoute: typeof AgentAgentIdRoute
  AgentPanelRoute: typeof AgentPanelRouteWithChildren
  AgentAgentIdSessionIdRoute: typeof AgentAgentIdSessionIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/agent/_panel": {
      id: "/agent/_panel"
      path: "/agent"
      fullPath: "/agent"
      preLoaderRoute: typeof AgentPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/agent/$agentId": {
      id: "/agent/$agentId"
      path: "/agent/$agentId"
      fullPath: "/agent/$agentId"
      preLoaderRoute: typeof AgentAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/workflow": {
      id: "/_app/workflow"
      path: "/workflow"
      fullPath: "/workflow"
      preLoaderRoute: typeof AppWorkflowRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/tasks": {
      id: "/_app/tasks"
      path: "/tasks"
      fullPath: "/tasks"
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/skills": {
      id: "/_app/skills"
      path: "/skills"
      fullPath: "/skills"
      preLoaderRoute: typeof AppSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/organizations": {
      id: "/_app/organizations"
      path: "/organizations"
      fullPath: "/organizations"
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/models": {
      id: "/_app/models"
      path: "/models"
      fullPath: "/models"
      preLoaderRoute: typeof AppModelsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/mcp": {
      id: "/_app/mcp"
      path: "/mcp"
      fullPath: "/mcp"
      preLoaderRoute: typeof AppMcpRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/knowledge-bases": {
      id: "/_app/knowledge-bases"
      path: "/knowledge-bases"
      fullPath: "/knowledge-bases"
      preLoaderRoute: typeof AppKnowledgeBasesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/environments": {
      id: "/_app/environments"
      path: "/environments"
      fullPath: "/environments"
      preLoaderRoute: typeof AppEnvironmentsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/channels": {
      id: "/_app/channels"
      path: "/channels"
      fullPath: "/channels"
      preLoaderRoute: typeof AppChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/apikeys": {
      id: "/_app/apikeys"
      path: "/apikeys"
      fullPath: "/apikeys"
      preLoaderRoute: typeof AppApikeysRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/agents": {
      id: "/_app/agents"
      path: "/agents"
      fullPath: "/agents"
      preLoaderRoute: typeof AppAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/$sessionId": {
      id: "/_app/$sessionId"
      path: "/$sessionId"
      fullPath: "/$sessionId"
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
    "/agent/_panel/": {
      id: "/agent/_panel/"
      path: "/"
      fullPath: "/agent/"
      preLoaderRoute: typeof AgentPanelIndexRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/workflow": {
      id: "/agent/_panel/workflow"
      path: "/workflow"
      fullPath: "/agent/workflow"
      preLoaderRoute: typeof AgentPanelWorkflowRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/tasks": {
      id: "/agent/_panel/tasks"
      path: "/tasks"
      fullPath: "/agent/tasks"
      preLoaderRoute: typeof AgentPanelTasksRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/skills": {
      id: "/agent/_panel/skills"
      path: "/skills"
      fullPath: "/agent/skills"
      preLoaderRoute: typeof AgentPanelSkillsRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/sessions": {
      id: "/agent/_panel/sessions"
      path: "/sessions"
      fullPath: "/agent/sessions"
      preLoaderRoute: typeof AgentPanelSessionsRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/organizations": {
      id: "/agent/_panel/organizations"
      path: "/organizations"
      fullPath: "/agent/organizations"
      preLoaderRoute: typeof AgentPanelOrganizationsRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/models": {
      id: "/agent/_panel/models"
      path: "/models"
      fullPath: "/agent/models"
      preLoaderRoute: typeof AgentPanelModelsRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/mcp": {
      id: "/agent/_panel/mcp"
      path: "/mcp"
      fullPath: "/agent/mcp"
      preLoaderRoute: typeof AgentPanelMcpRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/knowledge-bases": {
      id: "/agent/_panel/knowledge-bases"
      path: "/knowledge-bases"
      fullPath: "/agent/knowledge-bases"
      preLoaderRoute: typeof AgentPanelKnowledgeBasesRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/dashboard": {
      id: "/agent/_panel/dashboard"
      path: "/dashboard"
      fullPath: "/agent/dashboard"
      preLoaderRoute: typeof AgentPanelDashboardRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/channels": {
      id: "/agent/_panel/channels"
      path: "/channels"
      fullPath: "/agent/channels"
      preLoaderRoute: typeof AgentPanelChannelsRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/apikeys": {
      id: "/agent/_panel/apikeys"
      path: "/apikeys"
      fullPath: "/agent/apikeys"
      preLoaderRoute: typeof AgentPanelApikeysRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/$agentId_/$sessionId": {
      id: "/agent/$agentId_/$sessionId"
      path: "/agent/$agentId/$sessionId"
      fullPath: "/agent/$agentId/$sessionId"
      preLoaderRoute: typeof AgentAgentIdSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/workflow_/$": {
      id: "/_app/workflow_/$"
      path: "/workflow/$"
      fullPath: "/workflow/$"
      preLoaderRoute: typeof AppWorkflowSplatRouteImport
      parentRoute: typeof AppRoute
    }
    "/agent/_panel/chat/$agentId": {
      id: "/agent/_panel/chat/$agentId"
      path: "/chat/$agentId"
      fullPath: "/agent/chat/$agentId"
      preLoaderRoute: typeof AgentPanelChatAgentIdRouteImport
      parentRoute: typeof AgentPanelRoute
    }
    "/agent/_panel/chat/$agentId_/$sessionId": {
      id: "/agent/_panel/chat/$agentId_/$sessionId"
      path: "/chat/$agentId/$sessionId"
      fullPath: "/agent/chat/$agentId/$sessionId"
      preLoaderRoute: typeof AgentPanelChatAgentIdSessionIdRouteImport
      parentRoute: typeof AgentPanelRoute
    }
  }
}

interface AppRouteChildren {
  AppSessionIdRoute: typeof AppSessionIdRoute
  AppAgentsRoute: typeof AppAgentsRoute
  AppApikeysRoute: typeof AppApikeysRoute
  AppChannelsRoute: typeof AppChannelsRoute
  AppEnvironmentsRoute: typeof AppEnvironmentsRoute
  AppKnowledgeBasesRoute: typeof AppKnowledgeBasesRoute
  AppMcpRoute: typeof AppMcpRoute
  AppModelsRoute: typeof AppModelsRoute
  AppOrganizationsRoute: typeof AppOrganizationsRoute
  AppSkillsRoute: typeof AppSkillsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppWorkflowRoute: typeof AppWorkflowRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowSplatRoute: typeof AppWorkflowSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSessionIdRoute: AppSessionIdRoute,
  AppAgentsRoute: AppAgentsRoute,
  AppApikeysRoute: AppApikeysRoute,
  AppChannelsRoute: AppChannelsRoute,
  AppEnvironmentsRoute: AppEnvironmentsRoute,
  AppKnowledgeBasesRoute: AppKnowledgeBasesRoute,
  AppMcpRoute: AppMcpRoute,
  AppModelsRoute: AppModelsRoute,
  AppOrganizationsRoute: AppOrganizationsRoute,
  AppSkillsRoute: AppSkillsRoute,
  AppTasksRoute: AppTasksRoute,
  AppWorkflowRoute: AppWorkflowRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkflowSplatRoute: AppWorkflowSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AgentPanelRouteChildren {
  AgentPanelApikeysRoute: typeof AgentPanelApikeysRoute
  AgentPanelChannelsRoute: typeof AgentPanelChannelsRoute
  AgentPanelDashboardRoute: typeof AgentPanelDashboardRoute
  AgentPanelKnowledgeBasesRoute: typeof AgentPanelKnowledgeBasesRoute
  AgentPanelMcpRoute: typeof AgentPanelMcpRoute
  AgentPanelModelsRoute: typeof AgentPanelModelsRoute
  AgentPanelOrganizationsRoute: typeof AgentPanelOrganizationsRoute
  AgentPanelSessionsRoute: typeof AgentPanelSessionsRoute
  AgentPanelSkillsRoute: typeof AgentPanelSkillsRoute
  AgentPanelTasksRoute: typeof AgentPanelTasksRoute
  AgentPanelWorkflowRoute: typeof AgentPanelWorkflowRoute
  AgentPanelIndexRoute: typeof AgentPanelIndexRoute
  AgentPanelChatAgentIdRoute: typeof AgentPanelChatAgentIdRoute
  AgentPanelChatAgentIdSessionIdRoute: typeof AgentPanelChatAgentIdSessionIdRoute
}

const AgentPanelRouteChildren: AgentPanelRouteChildren = {
  AgentPanelApikeysRoute: AgentPanelApikeysRoute,
  AgentPanelChannelsRoute: AgentPanelChannelsRoute,
  AgentPanelDashboardRoute: AgentPanelDashboardRoute,
  AgentPanelKnowledgeBasesRoute: AgentPanelKnowledgeBasesRoute,
  AgentPanelMcpRoute: AgentPanelMcpRoute,
  AgentPanelModelsRoute: AgentPanelModelsRoute,
  AgentPanelOrganizationsRoute: AgentPanelOrganizationsRoute,
  AgentPanelSessionsRoute: AgentPanelSessionsRoute,
  AgentPanelSkillsRoute: AgentPanelSkillsRoute,
  AgentPanelTasksRoute: AgentPanelTasksRoute,
  AgentPanelWorkflowRoute: AgentPanelWorkflowRoute,
  AgentPanelIndexRoute: AgentPanelIndexRoute,
  AgentPanelChatAgentIdRoute: AgentPanelChatAgentIdRoute,
  AgentPanelChatAgentIdSessionIdRoute: AgentPanelChatAgentIdSessionIdRoute,
}

const AgentPanelRouteWithChildren = AgentPanelRoute._addFileChildren(
  AgentPanelRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AgentAgentIdRoute: AgentAgentIdRoute,
  AgentPanelRoute: AgentPanelRouteWithChildren,
  AgentAgentIdSessionIdRoute: AgentAgentIdSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
